Prepare SMSD 7.1.2 with CDK 2.13 and search correctness fixes

diff --git a/src/scripts/smsd b/src/scripts/smsd
--- a/src/scripts/smsd
+++ b/src/scripts/smsd
@@ -1,128 +1,20 @@
-#!/usr/bin/env sh
-# ----------------------------------------------------------------------------
-#  Copyright 2001-2006 The Apache Software Foundation.
-#
-#  Licensed under the Apache License, Version 2.0 (the "License");
-#  you may not use this file except in compliance with the License.
-#  You may obtain a copy of the License at
-#
-#       http://www.apache.org/licenses/LICENSE-2.0
-#
-#  Unless required by applicable law or agreed to in writing, software
-#  distributed under the License is distributed on an "AS IS" BASIS,
-#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-#  See the License for the specific language governing permissions and
-#  limitations under the License.
-# ----------------------------------------------------------------------------
-#
-#   Copyright (c) 2001-2006 The Apache Software Foundation.  All rights
-#   reserved.
-
-
-# resolve links - $0 may be a softlink
-PRG="$0"
-
-while [ -h "$PRG" ]; do
-  ls=`ls -ld "$PRG"`
-  link=`expr "$ls" : '.*-> \(.*\)$'`
-  if expr "$link" : '/.*' > /dev/null; then
-    PRG="$link"
-  else
-    PRG=`dirname "$PRG"`/"$link"
-  fi
-done
-
-PRGDIR=`dirname "$PRG"`
-BASEDIR=`cd "$PRGDIR/.." >/dev/null; pwd`
-
-# Reset the REPO variable. If you need to influence this use the environment setup file.
-REPO=
-
-
-# OS specific support.  $var _must_ be set to either true or false.
-cygwin=false;
-darwin=false;
-case "`uname`" in
-  CYGWIN*) cygwin=true ;;
-  Darwin*) darwin=true
-           if [ -z "$JAVA_VERSION" ] ; then
-             JAVA_VERSION="CurrentJDK"
-           else
-             echo "Using Java version: $JAVA_VERSION"
-           fi
-		   if [ -z "$JAVA_HOME" ]; then
-		      if [ -x "/usr/libexec/java_home" ]; then
-			      JAVA_HOME=`/usr/libexec/java_home`
-			  else
-			      JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/${JAVA_VERSION}/Home
-			  fi
-           fi       
-           ;;
-esac
-
-if [ -z "$JAVA_HOME" ] ; then
-  if [ -r /etc/gentoo-release ] ; then
-    JAVA_HOME=`java-config --jre-home`
-  fi
-fi
-
-# For Cygwin, ensure paths are in UNIX format before anything is touched
-if $cygwin ; then
-  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
-  [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
-fi
-
-# If a specific java binary isn't specified search for the standard 'java' binary
-if [ -z "$JAVACMD" ] ; then
-  if [ -n "$JAVA_HOME"  ] ; then
-    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
-      # IBM's JDK on AIX uses strange locations for the executables
-      JAVACMD="$JAVA_HOME/jre/sh/java"
-    else
-      JAVACMD="$JAVA_HOME/bin/java"
+#!/usr/bin/env bash
+# SMSD standalone CLI launcher. JAVA_OPTS is split on whitespace.
+set -eo pipefail
+SMSD_SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
+SMSD_JAR_PATH="${SMSD_JAR:-}"
+if [[ -z "$SMSD_JAR_PATH" ]]; then
+  for SMSD_CANDIDATE in "$SMSD_SCRIPT_DIR/../../target/"smsd-*-jar-with-dependencies.jar "$SMSD_SCRIPT_DIR/"smsd-*-jar-with-dependencies.jar; do
+    if [[ -f "$SMSD_CANDIDATE" ]] && { [[ -z "$SMSD_JAR_PATH" ]] || [[ "$SMSD_CANDIDATE" -nt "$SMSD_JAR_PATH" ]]; }; then
+      SMSD_JAR_PATH="$SMSD_CANDIDATE"
     fi
-  else
-    JAVACMD=`which java`
-  fi
+  done
 fi
-
-if [ ! -x "$JAVACMD" ] ; then
-  echo "Error: JAVA_HOME is not defined correctly." 1>&2
-  echo "  We cannot execute $JAVACMD" 1>&2
+if [[ ! -f "$SMSD_JAR_PATH" ]]; then
+  echo "SMSD JAR not found. Run 'mvn package' first or set SMSD_JAR." >&2
   exit 1
 fi
-
-if [ -z "$REPO" ]
-then
-  REPO="$BASEDIR"/repo
-fi
-
-CLASSPATH="$BASEDIR"/etc:"$REPO"/*
-
-ENDORSED_DIR=
-if [ -n "$ENDORSED_DIR" ] ; then
-  CLASSPATH=$BASEDIR/$ENDORSED_DIR/*:$CLASSPATH
-fi
-
-if [ -n "$CLASSPATH_PREFIX" ] ; then
-  CLASSPATH=$CLASSPATH_PREFIX:$CLASSPATH
-fi
-
-# For Cygwin, switch paths to Windows format before running java
-if $cygwin; then
-  [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
-  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
-  [ -n "$HOME" ] && HOME=`cygpath --path --windows "$HOME"`
-  [ -n "$BASEDIR" ] && BASEDIR=`cygpath --path --windows "$BASEDIR"`
-  [ -n "$REPO" ] && REPO=`cygpath --path --windows "$REPO"`
-fi
-
-exec "$JAVACMD" $JAVA_OPTS  \
-  -classpath "$CLASSPATH" \
-  -Dapp.name="smsd" \
-  -Dapp.pid="$$" \
-  -Dapp.repo="$REPO" \
-  -Dapp.home="$BASEDIR" \
-  -Dbasedir="$BASEDIR" \
-  com.bioinception.smsd.cli.SMSDcli \
-  "$@"
+SMSD_JAVA=java
+if [[ -n "${JAVA_HOME:-}" ]]; then SMSD_JAVA="$JAVA_HOME/bin/java"; fi
+read -r -a SMSD_JAVA_OPTIONS <<< "${JAVA_OPTS:-}"
+exec "$SMSD_JAVA" "${SMSD_JAVA_OPTIONS[@]}" -jar "$SMSD_JAR_PATH" "$@"
